package com.elseeker.android.feature.study.ui.content

/** 성경 역사(연대·사건) — 원본: HistoryViewResponse.kt 의 HistoryDummyData. 텍스트는 원문 그대로. */
internal val historyContent: StudyContentItem = StudyContentItem(
    key = "history",
    title = "성경 역사",
    subtitle = "연대·사건·상세",
    track = StudyTrack.S1,
    ready = true,
    historyTitle = "시대 구분",
    history = listOf(
        StudySection("창조와 족장 시대 (연대 미상)", "핵심 키워드: 창조, 언약"),
        StudySection("출애굽과 광야 (B.C 1500-1300)", "핵심 키워드: 해방, 광야"),
        StudySection("가나안 정복 (B.C 1400-1200)", "핵심 키워드: 여호수아, 정복"),
        StudySection("사사 시대 (B.C 1200-1050)", "핵심 키워드: 사사, 순환"),
        StudySection("통일 왕국 시대 (B.C 1050-930)", "핵심 키워드: 다윗, 솔로몬"),
        StudySection("분열 왕국 시대 (B.C 930-586)", "핵심 키워드: 북이스라엘, 남유다"),
        StudySection("바벨론 포로 (B.C 586-539)", "핵심 키워드: 바벨론, 포로"),
        StudySection("귀환과 재건 (B.C 538-430)", "핵심 키워드: 예루살렘, 성전"),
        StudySection("중간사 시대 (B.C 400-4)", "핵심 키워드: 헬라, 로마"),
        StudySection("예수 시대 (B.C 4-A.D 30)", "핵심 키워드: 복음, 구원"),
        StudySection("초대 교회 (A.D 33-100)", "핵심 키워드: 사도, 선교"),
        StudySection("창조와 족장 시대 관련 성경책", "율법서: 창세기 / 시가서: 욥기"),
        StudySection("출애굽과 광야 관련 성경책", "율법서: 출애굽기, 레위기, 민수기, 신명기"),
        StudySection("가나안 정복 관련 성경책", "역사서: 여호수아"),
        StudySection("사사 시대 관련 성경책", "역사서: 사사기, 룻기"),
        StudySection("통일 왕국 시대 관련 성경책", "역사서: 사무엘상, 사무엘하, 열왕기상 / 시가서: 시편, 아가"),
        StudySection("분열 왕국 시대 관련 성경책", "역사서: 열왕기하, 역대상, 역대하 / 예언서: 이사야, 예레미야, 호세아, 아모스"),
        StudySection("바벨론 포로 관련 성경책", "예언서: 예레미야, 예레미야애가, 에스겔, 다니엘"),
        StudySection("귀환과 재건 관련 성경책", "역사서: 에스라, 느헤미야, 에스더 / 예언서: 학개, 스가랴, 말라기"),
        StudySection("중간사 시대 관련 성경책", "배경: 헬라 시대, 로마 시대"),
        StudySection("예수 시대 관련 성경책", "복음서: 마태복음, 마가복음, 누가복음, 요한복음"),
        StudySection("초대 교회 관련 성경책", "역사서: 사도행전 / 서신서: 로마서, 고린도전서, 갈라디아서, 에베소서"),
    ),
    cardsTitle = "주요 사건",
    cards = listOf(
        StudyCard(
            tag = "창조와 족장 시대",
            title = "창조",
            meaning = "하나님이 세상을 창조하신 사건.",
            relatedVerse = "창 1-2",
        ),
        StudyCard(
            tag = "창조와 족장 시대",
            title = "아브라함 언약",
            meaning = "믿음의 조상 아브라함에게 주어진 언약.",
            relatedVerse = "창 12, 15, 17",
        ),
        StudyCard(
            tag = "출애굽과 광야",
            title = "출애굽",
            meaning = "애굽에서 해방되어 광야로 나아간 사건.",
            relatedVerse = "출 1-15",
        ),
        StudyCard(
            tag = "출애굽과 광야",
            title = "시내산 언약",
            meaning = "율법이 주어지고 언약이 갱신된 사건.",
            relatedVerse = "출 19-24",
        ),
        StudyCard(
            tag = "가나안 정복",
            title = "여리고 함락",
            meaning = "가나안 정복의 첫 전투로 여리고성이 무너짐.",
            relatedVerse = "수 6",
        ),
        StudyCard(
            tag = "사사 시대",
            title = "기드온의 승리",
            meaning = "적은 군대로 미디안을 이긴 사건.",
            relatedVerse = "삿 6-7",
        ),
        StudyCard(
            tag = "통일 왕국 시대",
            title = "다윗 왕국",
            meaning = "예루살렘을 중심으로 통일 왕국이 세워짐.",
            relatedVerse = "삼하 5-7",
        ),
        StudyCard(
            tag = "통일 왕국 시대",
            title = "솔로몬 성전 봉헌",
            meaning = "첫 성전이 완공되어 봉헌됨.",
            relatedVerse = "왕상 8",
        ),
        StudyCard(
            tag = "분열 왕국 시대",
            title = "엘리야의 갈멜 산 대결",
            meaning = "바알 선지자와의 대결로 하나님을 증명.",
            relatedVerse = "왕상 18",
        ),
        StudyCard(
            tag = "분열 왕국 시대",
            title = "북이스라엘 멸망",
            meaning = "앗수르에 의해 북이스라엘이 멸망함.",
            relatedVerse = "왕하 17",
        ),
        StudyCard(
            tag = "바벨론 포로",
            title = "바벨론 포로 시작",
            meaning = "유다 백성이 바벨론으로 끌려감.",
            relatedVerse = "왕하 24",
        ),
        StudyCard(
            tag = "바벨론 포로",
            title = "예루살렘 성전 파괴",
            meaning = "바벨론에 의해 성전이 파괴됨.",
            relatedVerse = "왕하 25",
        ),
        StudyCard(
            tag = "귀환과 재건",
            title = "스룹바벨 1차 귀환",
            meaning = "포로에서 돌아와 예배를 회복함.",
            relatedVerse = "스 1-3",
        ),
        StudyCard(
            tag = "귀환과 재건",
            title = "느헤미야 성벽 재건",
            meaning = "예루살렘 성벽이 재건됨.",
            relatedVerse = "느 1-6",
        ),
        StudyCard(
            tag = "중간사 시대",
            title = "마카비 혁명",
            meaning = "헬라 통치에 맞서 유대 독립을 회복.",
            relatedVerse = "외경 배경",
        ),
        StudyCard(
            tag = "예수 시대",
            title = "예수 탄생",
            meaning = "메시아의 탄생과 복음의 시작.",
            relatedVerse = "마 1-2, 눅 1-2",
        ),
        StudyCard(
            tag = "예수 시대",
            title = "십자가와 부활",
            meaning = "예수님의 죽음과 부활로 구원이 완성.",
            relatedVerse = "마 27-28",
        ),
        StudyCard(
            tag = "초대 교회",
            title = "오순절 성령 강림",
            meaning = "성령이 임하여 교회가 탄생함.",
            relatedVerse = "행 2",
        ),
        StudyCard(
            tag = "초대 교회",
            title = "바울 1차 선교",
            meaning = "복음이 이방으로 확장됨.",
            relatedVerse = "행 13-14",
        ),
    ),
)
