package com.elseeker.android.feature.study.ui.content

/** 성경 개요 영상(66권) — 원본: static/js/study/bible-overview-video.js. S2 트랙. */
internal val overviewVideoContent: StudyContentItem = StudyContentItem(
    key = "overview-video",
    title = "성경 개요 영상",
    subtitle = "66권 개요 영상",
    track = StudyTrack.S2,
    ready = true,
    linksTitle = "책별 개요 영상 (유튜브)",
    links = listOf(
        StudyLink(title = "창세기", subtitle = "구약", url = "https://youtu.be/dLv2ndgXrbo?si=sJmYqcu0vhoJdBKB"),
        StudyLink(title = "출애굽기", subtitle = "구약", url = "https://youtu.be/PrTbYx6KbtY?si=Xo6fG7ECW1_ozIek"),
        StudyLink(title = "레위기", subtitle = "구약", url = "https://youtu.be/OUPcm3QGt7Y?si=eVht_QCA11EVStth"),
        StudyLink(title = "민수기", subtitle = "구약", url = "https://youtu.be/Q0Lac54urBU?si=CgpRmPOwBzQebdun"),
        StudyLink(title = "신명기", subtitle = "구약", url = "https://youtu.be/HOA8818FdYc?si=EIKshhqyR1HbZQy3"),
        StudyLink(title = "여호수아", subtitle = "구약", url = "https://youtu.be/9MmKvOItPds?si=CIUk6-yeQQGXh0CS"),
        StudyLink(title = "사사기", subtitle = "구약", url = "https://youtu.be/2rnPxn2aeN0?si=UFWrgTdLtMJrjEMh"),
        StudyLink(title = "룻기", subtitle = "구약", url = "https://youtu.be/jB2au0FGgjo?si=DtsVq0Pl7i7Osroq"),
        StudyLink(title = "사무엘상", subtitle = "구약", url = "https://youtu.be/gZ9Jf2FeZJQ?si=yVkIRcbA9Sk1SDNp"),
        StudyLink(title = "사무엘하", subtitle = "구약", url = "https://youtu.be/QYuSYPIfFPA?si=j2NX-_j20s75TCYu"),
        StudyLink(title = "열왕기상", subtitle = "구약", url = "https://youtu.be/jIcsdztsKBE?si=mO2SmJDugqr5Kjfv"),
        StudyLink(title = "열왕기하", subtitle = "구약", url = "https://youtu.be/jIcsdztsKBE?si=mO2SmJDugqr5Kjfv"),
        StudyLink(title = "역대상", subtitle = "구약", url = "https://youtu.be/AgRvk1qOAgg?si=DbkCoJM56gGJ6ICk"),
        StudyLink(title = "역대하", subtitle = "구약", url = "https://youtu.be/AgRvk1qOAgg?si=DbkCoJM56gGJ6ICk"),
        StudyLink(title = "에스라", subtitle = "구약", url = "https://youtu.be/IxHJN4cOl-c?si=F-fnWC8aEmmgy1Rk"),
        StudyLink(title = "느헤미야", subtitle = "구약", url = "https://youtu.be/IxHJN4cOl-c?si=F-fnWC8aEmmgy1Rk"),
        StudyLink(title = "에스더", subtitle = "구약", url = "https://youtu.be/e4rGAPgtBbc?si=WvGLMaWidBbLIT7T"),
        StudyLink(title = "욥기", subtitle = "구약", url = "https://youtu.be/SoOSMWGuDxk?si=4Nx9oF4P8n_hiE3Y"),
        StudyLink(title = "시편", subtitle = "구약", url = "https://youtu.be/amAZ8ewil7g?si=RWDtLgCS666-3M9S"),
        StudyLink(title = "잠언", subtitle = "구약", url = "https://youtu.be/WPAs3uHoPDI?si=6csGm0l6UBXRt591"),
        StudyLink(title = "전도서", subtitle = "구약", url = "https://youtu.be/8bnFXIKuq3U?si=XhEw0dhi0m1n5rFU"),
        StudyLink(title = "아가", subtitle = "구약", url = "https://youtu.be/jLA7P-L9NgU?si=kDFVgbIysy81Us3C"),
        StudyLink(title = "이사야", subtitle = "구약", url = "https://youtu.be/b0-A9qEu5ug?si=hrNPdF_Uc-3jQfrU"),
        StudyLink(title = "예레미야", subtitle = "구약", url = "https://youtu.be/ErL1bUKQIIY?si=yQrrNkRb0qYAWuoG"),
        StudyLink(title = "예레미야애가", subtitle = "구약", url = "https://youtu.be/twumxE5HxYU?si=auzxl_m-vb6W0ffu"),
        StudyLink(title = "에스겔", subtitle = "구약", url = "https://youtu.be/IO9XplZBcvk?si=Q5bfioLqzLdZBMqN"),
        StudyLink(title = "다니엘", subtitle = "구약", url = "https://youtu.be/clI5OYY4lVo?si=w8GpMUEYIlZf_333"),
        StudyLink(title = "호세아", subtitle = "구약", url = "https://youtu.be/M669lzWgN5k?si=1Y-GIRxAYjI0TyiI"),
        StudyLink(title = "요엘", subtitle = "구약", url = "https://youtu.be/4ucQjbVb4oE?si=ny8qt0IoNuhPShYG"),
        StudyLink(title = "아모스", subtitle = "구약", url = "https://youtu.be/FOH4qvNr9O8?si=hWIcBPMGe1dVDmgN"),
        StudyLink(title = "오바댜", subtitle = "구약", url = "https://youtu.be/znmT4B8j4xA?si=ThMplhyNo4z0GKDn"),
        StudyLink(title = "요나", subtitle = "구약", url = "https://youtu.be/P6bSRsI4rY0?si=8ZGXs7gSk_IUDp2o"),
        StudyLink(title = "미가", subtitle = "구약", url = "https://youtu.be/cES-IDPeU4E?si=6Sab8VuetOXHUhg1"),
        StudyLink(title = "나훔", subtitle = "구약", url = "https://youtu.be/qhJQqrm2pUw?si=K5HHEPi1mr5bDwWO"),
        StudyLink(title = "하박국", subtitle = "구약", url = "https://youtu.be/BRbdfL0u4hQ?si=OWredLuwEiy-_HUl"),
        StudyLink(title = "스바냐", subtitle = "구약", url = "https://youtu.be/WWIQaLlsCjo?si=U1dEH8tZj4FmViwp"),
        StudyLink(title = "학개", subtitle = "구약", url = "https://youtu.be/j-S26FNz_XY?si=-DCXCs-zmeEhglqu"),
        StudyLink(title = "스가랴", subtitle = "구약", url = "https://youtu.be/l8CdmoLKq3E?si=SpdQ-zUg0GGwlCh2"),
        StudyLink(title = "말라기", subtitle = "구약", url = "https://youtu.be/KxJb21AxVqI?si=eg9aaKRDjzMM-WKl"),
        StudyLink(title = "마태복음", subtitle = "신약", url = "https://youtu.be/cbabreYd34Q?si=EphYGrZe4NpiTPAZ"),
        StudyLink(title = "마가복음", subtitle = "신약", url = "https://youtu.be/hKtkrVwvFoo?si=hLWtNwMV3bRjGchs"),
        StudyLink(title = "누가복음", subtitle = "신약", url = "https://youtu.be/szex2l67GwQ?si=LAm_zPfs0NGpQkWI"),
        StudyLink(title = "요한복음", subtitle = "신약", url = "https://youtu.be/FV55I_rX4Kg?si=iVtQVscV-w9culCm"),
        StudyLink(title = "사도행전", subtitle = "신약", url = "https://youtu.be/kOCqsPst9Ag?si=3Cvcnh021APNElhs"),
        StudyLink(title = "로마서", subtitle = "신약", url = "https://youtu.be/PT4C0ley074?si=53vTkQrIngpYIwnk"),
        StudyLink(title = "고린도전서", subtitle = "신약", url = "https://youtu.be/SoxLSx5DOjg?si=k0EgqKkHRg5a5SM7"),
        StudyLink(title = "고린도후서", subtitle = "신약", url = "https://youtu.be/xZFXdP7CCcc?si=VAnxhV0fJ8wbY0bl"),
        StudyLink(title = "갈라디아서", subtitle = "신약", url = "https://youtu.be/IRaMP5i4ROc?si=iAcgoMxfjAhagzRk"),
        StudyLink(title = "에베소서", subtitle = "신약", url = "https://youtu.be/1Cvb3mjw7WQ?si=hE4cVlGtU1gdgSGd"),
        StudyLink(title = "빌립보서", subtitle = "신약", url = "https://youtu.be/P2stOv4EuD8?si=alrr0SBbo-7Et_nx"),
        StudyLink(title = "골로새서", subtitle = "신약", url = "https://youtu.be/PToo8H3ESmI?si=OlgLQIjZRxGA10LQ"),
        StudyLink(title = "데살로니가전서", subtitle = "신약", url = "https://youtu.be/78mjPkm3gNU?si=hpBcGWkde1pr1xh4"),
        StudyLink(title = "데살로니가후서", subtitle = "신약", url = "https://youtu.be/aSvUcBhd4hQ?si=5Jxi0LlA09vZZurI"),
        StudyLink(title = "디모데전서", subtitle = "신약", url = "https://youtu.be/TPaaXttsgzY?si=BcHNsmJzwcjQYEz3"),
        StudyLink(title = "디모데후서", subtitle = "신약", url = "https://youtu.be/2rbLGN90JyE?si=fVapJBla3MbLQj0f"),
        StudyLink(title = "디도서", subtitle = "신약", url = "https://youtu.be/tdTrkbn8plI?si=iQgG7r9Gek6k06ig"),
        StudyLink(title = "빌레몬서", subtitle = "신약", url = "https://youtu.be/FF52ylLRH3g?si=ZbTkr34dzX_T0npL"),
        StudyLink(title = "히브리서", subtitle = "신약", url = "https://youtu.be/_y4X0Y1nu5E?si=SYd1VjlQHZtU-CFc"),
        StudyLink(title = "야고보서", subtitle = "신약", url = "https://youtu.be/PKic-DpY3O4?si=d248N_38IUJUKBO2"),
        StudyLink(title = "베드로전서", subtitle = "신약", url = "https://youtu.be/5te24c_61aI?si=MV_X3Kd4qYRa2Che"),
        StudyLink(title = "베드로후서", subtitle = "신약", url = "https://youtu.be/Ii-v2hGv-zk?si=C93Z5HtM8xpAe5Ux"),
        StudyLink(title = "요한1서", subtitle = "신약", url = "https://youtu.be/cMKPbDZhToo?si=I-SO7O8SGtdhLWGJ"),
        StudyLink(title = "요한2서", subtitle = "신약", url = "https://youtu.be/cMKPbDZhToo?si=I-SO7O8SGtdhLWGJ"),
        StudyLink(title = "요한3서", subtitle = "신약", url = "https://youtu.be/cMKPbDZhToo?si=I-SO7O8SGtdhLWGJ"),
        StudyLink(title = "유다서", subtitle = "신약", url = "https://youtu.be/ggYH-spyKHY?si=ku7cTUbVsFJBO67D"),
        StudyLink(title = "요한계시록", subtitle = "신약", url = "https://youtu.be/ue4ZFykrMJ8?si=b1XSktafOvar288A"),
    ),
)
