package com.elseeker.android.feature.study.ui.content

/** 공동체성경읽기(PRS) 드라마바이블 영상 — 원본: static/js/study/public-reading-of-scripture.js. */
internal val publicReadingContent: StudyContentItem = StudyContentItem(
    key = "public-reading",
    title = "공동체 성경읽기",
    subtitle = "드라마바이블 영상 66권",
    track = StudyTrack.S1,
    ready = true,
    paragraphs = listOf(
        "공동체성경읽기(PRS) 드라마바이블 영상을 성경 책별로 시청할 수 있는 학습 페이지입니다. 전문 배우와 성우의 낭독, OST, 효과음으로 몰입감 있는 성경 통독을 경험하세요.",
    ),
    linksTitle = "책별 영상 (유튜브)",
    links = listOf(
        // ── 구약 (39권) ──
        StudyLink(title = "창세기", subtitle = "구약", url = "https://youtu.be/DaR5sH-036g?si=OLSn3Tya9WWA13Wu"),
        StudyLink(title = "출애굽기", subtitle = "구약", url = "https://youtu.be/ynUSXcluVAo?si=bTKBLHTXYSpAbhTF"),
        StudyLink(title = "레위기", subtitle = "구약", url = "https://youtu.be/T1Z4eTqGmVQ?si=bLfmqqFpedQ9DQLP"),
        StudyLink(title = "민수기", subtitle = "구약", url = "https://youtu.be/qtnNwCNCJRU?si=J2iJ02mXE5js8Uw1"),
        StudyLink(title = "신명기", subtitle = "구약", url = "https://youtu.be/wh1NX3XNqnQ?si=Pqdh8xeVgAsNbquo"),
        StudyLink(title = "여호수아", subtitle = "구약", url = "https://youtu.be/yVtvT5RG8J4?si=TznhYc-Cu9uAy3zL"),
        StudyLink(title = "사사기", subtitle = "구약", url = "https://youtu.be/Zpp6AJ60Y-k?si=Hpy5QeYvTJEDswFC"),
        StudyLink(title = "룻기", subtitle = "구약", url = "https://youtu.be/trV-U1bbVRk?si=BMoGE6ivwvnA9P9l"),
        StudyLink(title = "사무엘상", subtitle = "구약", url = "https://youtu.be/i0dn2e6A5MY?si=3y-pu0_xbswagTEN"),
        StudyLink(title = "사무엘하", subtitle = "구약", url = "https://youtu.be/o92ZqyPVCbo?si=iJYpmEo9a7XySApm"),
        StudyLink(title = "열왕기상", subtitle = "구약", url = "https://youtu.be/EafFiI-mBvw?si=ehsWbrO1xw-3BlJh"),
        StudyLink(title = "열왕기하", subtitle = "구약", url = "https://youtu.be/zJlhrABqfFs?si=65w8XMMAoRkFeMPC"),
        StudyLink(title = "역대상", subtitle = "구약", url = "https://youtu.be/D-5eUJj3BRY?si=_MoSVnUF4izfW18B"),
        StudyLink(title = "역대하", subtitle = "구약", url = "https://youtu.be/b9es4tKiIeA?si=-uuyqoSqlx5FZrEE"),
        StudyLink(title = "에스라", subtitle = "구약", url = "https://youtu.be/NwCG2t8tqBE?si=oymBcUyHJZZE5ta-"),
        StudyLink(title = "느헤미야", subtitle = "구약", url = "https://youtu.be/k45UVgehRuQ?si=BDvaBgqcQByvL9kR"),
        StudyLink(title = "에스더", subtitle = "구약", url = "https://youtu.be/Qj2pDvmvISA?si=nL4ews0SjeexAPj1"),
        StudyLink(title = "욥기", subtitle = "구약", url = "https://youtu.be/VRafPcNOh1o?si=Qyt5WtskKP7Pg_7K"),
        StudyLink(title = "시편", subtitle = "구약", url = "https://youtu.be/qZgejaNWe-w?si=TbjsrE2WK5AYhegY"),
        StudyLink(title = "잠언", subtitle = "구약", url = "https://youtu.be/vjXtoi_hRNU?si=pukA_9HWShpU1Xgb"),
        StudyLink(title = "전도서", subtitle = "구약", url = "https://youtu.be/1lH_YUAlgJY?si=RyujZhxsT4y8ot6U"),
        StudyLink(title = "아가", subtitle = "구약", url = "https://youtu.be/RssSfKX5deQ?si=dg4Zgzue_yuq3kFz"),
        StudyLink(title = "이사야", subtitle = "구약", url = "https://youtu.be/PrDrpjxHWFk?si=nwDIyeQovVBq3Vo-"),
        StudyLink(title = "예레미야", subtitle = "구약", url = "https://youtu.be/tFFDjFIBn28?si=xsGk4huJNwtETzIl"),
        StudyLink(title = "예레미야애가", subtitle = "구약", url = "https://youtu.be/MFFdjWzISgs?si=kR5tHG1D6r6ffm2h"),
        StudyLink(title = "에스겔", subtitle = "구약", url = "https://youtu.be/E2MnuODJOfE?si=BenmTZ3kISsIgbrt"),
        StudyLink(title = "다니엘", subtitle = "구약", url = "https://youtu.be/Kcs6FNfMYvY?si=ZqOeXXOvL6rWhm-c"),
        StudyLink(title = "호세아", subtitle = "구약", url = "https://youtu.be/4zyMY1DH1LM?si=hHtyB0iQDKGgVUZK"),
        StudyLink(title = "요엘", subtitle = "구약", url = "https://youtu.be/I1ZLDufpnPI?si=H-_InXlFYKuXNnMa"),
        StudyLink(title = "아모스", subtitle = "구약", url = "https://youtu.be/-0Ha51yyNIc?si=oyu2yr07h2br-jEX"),
        StudyLink(title = "오바댜", subtitle = "구약", url = "https://youtu.be/9OZxEC6PuyE?si=5YXSHX9yOPGpERpF"),
        StudyLink(title = "요나", subtitle = "구약", url = "https://youtu.be/a8UTxG5wRfw?si=L1opg7GBm8lgORdZ"),
        StudyLink(title = "미가", subtitle = "구약", url = "https://youtu.be/XWhMLn003ss?si=hifj5CJtlIFQsS27"),
        StudyLink(title = "나훔", subtitle = "구약", url = "https://youtu.be/JfnTf8lI-xc?si=TokoVHxkIatvs00B"),
        StudyLink(title = "하박국", subtitle = "구약", url = "https://youtu.be/yUmcNBjHjAM?si=72kB6U9X77pvyA3E"),
        StudyLink(title = "스바냐", subtitle = "구약", url = "https://youtu.be/9NIQvuOuORE?si=vDQ_i_9NxxcxvYAQ"),
        StudyLink(title = "학개", subtitle = "구약", url = "https://youtu.be/SXgLWOrPPoY?si=SVgjSZ5NRMyCJDwq"),
        StudyLink(title = "스가랴", subtitle = "구약", url = "https://youtu.be/7nmICiGfGTM?si=gzjngrDJq1juafGl"),
        StudyLink(title = "말라기", subtitle = "구약", url = "https://youtu.be/niU_fW1auu4?si=ZZuQEkvyHmLHaUPx"),
        // ── 신약 (27권) ──
        StudyLink(title = "마태복음", subtitle = "신약", url = "https://youtu.be/BA61xFXBwCo?si=hzDpQcX3A9ZtR5Kb"),
        StudyLink(title = "마가복음", subtitle = "신약", url = "https://youtu.be/6odQgUVVFLU?si=lllouyEIi8rN_wHw"),
        StudyLink(title = "누가복음", subtitle = "신약", url = "https://youtu.be/c_y1TrISUXs?si=fOYAsG-wWB9phDRo"),
        StudyLink(title = "요한복음", subtitle = "신약", url = "https://youtu.be/2UD9qiRp6B0?si=mVDrZKdCR2-trHbG"),
        StudyLink(title = "사도행전", subtitle = "신약", url = "https://youtu.be/jVO5lOOS37w?si=G_oQmAyZ461MbP1K"),
        StudyLink(title = "로마서", subtitle = "신약", url = "https://youtu.be/zDVkOQYmI0o?si=mMHJVwn7wjOiVK_k"),
        StudyLink(title = "고린도전서", subtitle = "신약", url = "https://youtu.be/EKoXIgVMv6Y?si=LmiXDLs0Z7t7Hnzt"),
        StudyLink(title = "고린도후서", subtitle = "신약", url = "https://youtu.be/pecL1Uk1fLE?si=pgn9n_ImCJ_SA_70"),
        StudyLink(title = "갈라디아서", subtitle = "신약", url = "https://youtu.be/fj0rAyMYeow?si=aCK6Rj5gMDj6YQTF"),
        StudyLink(title = "에베소서", subtitle = "신약", url = "https://youtu.be/LbquANbw0T0?si=yyXfhNAuzbolCWL0"),
        StudyLink(title = "빌립보서", subtitle = "신약", url = "https://youtu.be/4teyRYSKFGk?si=lkMfPq8CIRpv2zx6"),
        StudyLink(title = "골로새서", subtitle = "신약", url = "https://youtu.be/-ug5pvxvnUA?si=Gzuti1gVZhEIqx-X"),
        StudyLink(title = "데살로니가전서", subtitle = "신약", url = "https://youtu.be/kW1KDmsR4Hg?si=vaZAjik_xlsVlOFP"),
        StudyLink(title = "데살로니가후서", subtitle = "신약", url = "https://youtu.be/lafvlswau-Q?si=ptJapkNdaxJbUcmg"),
        StudyLink(title = "디모데전서", subtitle = "신약", url = "https://youtu.be/bZBDM2lTPYg?si=bA5IYRY718yDtQmu"),
        StudyLink(title = "디모데후서", subtitle = "신약", url = "https://youtu.be/Wmp4mjDioCs?si=RAYic8lpE98WOaBC"),
        StudyLink(title = "디도서", subtitle = "신약", url = "https://youtu.be/XDhX2VJl0D4?si=dJW0plknjnCoMqXa"),
        StudyLink(title = "빌레몬서", subtitle = "신약", url = "https://youtu.be/JW8aOeWaiWU?si=L3QtLZNzSbBWbt26"),
        StudyLink(title = "히브리서", subtitle = "신약", url = "https://youtu.be/ouVU9S6r7Qw?si=TRnpSqABRKwoRTbU"),
        StudyLink(title = "야고보서", subtitle = "신약", url = "https://youtu.be/KB4oyzTsKjQ?si=XJtg74Phgm7U4ek5"),
        StudyLink(title = "베드로전서", subtitle = "신약", url = "https://youtu.be/v-yh2bDVHY8?si=b4W2j-9aBr8LjejV"),
        StudyLink(title = "베드로후서", subtitle = "신약", url = "https://youtu.be/1e4pjWtYgUI?si=gZraC5p-MMeczA5N"),
        StudyLink(title = "요한1서", subtitle = "신약", url = "https://youtu.be/hpX4oQdmV78?si=Zw1qgfyz2r3WSOWx"),
        StudyLink(title = "요한2서", subtitle = "신약", url = "https://youtu.be/TBgQSyXViU0?si=TiGod4k4j-6Je3C-"),
        StudyLink(title = "요한3서", subtitle = "신약", url = "https://youtu.be/1vAdhS1KctY?si=HZozdfx3jzjUcr0K"),
        StudyLink(title = "유다서", subtitle = "신약", url = "https://youtu.be/QTrzN5zdZMA?si=gMG116WcVGAST-m0"),
        StudyLink(title = "요한계시록", subtitle = "신약", url = "https://youtu.be/sPFEROfY2AY?si=N1pLIApE9tfD1Dxi"),
    ),
)
